config/routes.rb
Rails.application.routes.draw do

  devise_for :companies ,controllers: {
                 sessions: "companies/sessions",
                 registrations: "companies/registrations"

                        }
  devise_for :users ,controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations"

              }

  root 'welcome#index'

  get  '/vacancy'   =>  'vacancy#index'

  post  '/vacancy/search' => 'vacancy#search'
  get  '/vacancy/search' => 'vacancy#search'

  get  '/vacancy/show'  => 'vacancy#show'

  post '/vacancy/sub_resume' => 'vacancy#sub_resume'

  get  '/resume'     =>'resume#index'
  post '/resume/create_base_info' => 'resume#create_base_info'
  post  '/resume/create_contact'  =>'resume#create_contact'

  post  '/resume/create_edu'   => 'resume#create_edu'
  get '/resume/delete_edu'   =>'resume#delete_edu'
  get  '/resume/edit_edu'   =>'resume#edit_edu'
  post  'resume/update_edu' =>'resume#update_edu'

  post  '/resume/create_exp' =>'resume#create_exp'
  get  '/resume/edit_exp'  => 'resume#edit_exp'
  post '/resume/update_exp' =>'resume#update_exp'
  get  '/resume/delete_exp'  => 'resume#delete_exp'

  post '/resume/create_avatar' => 'resume#create_avatar'

  get 'resume/show'   =>  'resume#show'

  get '/interview'   => 'interview#index'
  get '/interview/invite/:id' =>'interview#invite'

  get '/interview/refuse/:id' => 'interview#refuse'

    get '/company'  => 'company#index'

end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  skip_before_filter :verify_authenticity_token

  before_action :authenticate_user! 

  def index

    @hotjob=Job.find_by_sql("select * from jobs where id < 3")

    @goodjob=Job.find [1,3,5,6]

    @base_info=BaseInfo.find_by_user_id(current_user.id)

    @contact=Contact.find_by_user_id(current_user.id)

    @edu =Education.where(:user_id => current_user.id)


    @exp =Experience.where(:user_id => current_user.id)



  end

  def show


    @base_info=BaseInfo.find_by_user_id(params[:user_id])

    @contact=Contact.find_by_user_id(params[:user_id])

    @edu =Education.where(:user_id => params[:user_id])


    @exp =Experience.where(:user_id => params[:user_id])


    @Interview= Interview.where(:user_id => params[:user_id],:resume_id => params[:resume_id])

    return render 'resume/show'


  end




  def create_base_info

     @base=BaseInfo.find_by_user_id(current_user.id)


     if @base.nil?

       @base=BaseInfo.new base_info_params
       @base.user_id=current_user.id
       @base.province=params[:cho_Province]
       @base.city=params[:cho_City]
       @base.city=params[:cho_Area]
       @base.save
     else

       @base.update(base_info_params)
       @base.update(:province => params[:cho_Province],:city => params[:cho_City],:area=> params[:cho_Area])

     end





    redirect_to  "/resume"

  end

  def create_contact


    @contact=Contact.find_by_user_id(current_user.id)

    if !@contact.nil?

      @contact.update(contact_params)

    else

      @contact=Contact.new contact_params

      @contact.user_id=current_user.id

      @contact.save

    end



  redirect_to "/resume"

  end


  def create_edu



      @edu =Education.new edu_params

      @edu.user_id = current_user.id

      @edu.save


    redirect_to "/resume"

  end

  def edit_edu

    @edu =Education.find_by_id(params[:id])

     return render :json => {:school => @edu.school ,:end_time => @edu.end_time ,:begin_time => @edu.begin_time,
                              :level => @edu.level ,:profession => @edu.profession }

  end

  def update_edu

    @edu = Education.find_by_id(params[:id])


    @edu.update(edu_params)


    redirect_to "/resume"

  end

  def delete_edu

   @edu=Education.find_by_id(params[:id])

   @edu.destroy


    redirect_to "/resume"

  end

  def create_exp
    @exp=Experience.new exp_params

    @exp.user_id=current_user.id

    @exp.save

    redirect_to "/resume"

  end


  def delete_exp

  @exp=Experience.find_by_id(params[:id])

  @exp.destroy


    redirect_to "/resume"


  end
  def edit_exp

    @exp=Experience.find_by_id(params[:id])


    return render :json => {:company => @exp.company, :work => @exp.work, :end_time => @exp.end_time ,:begin_time =>@exp.begin_time,

                            :work_type => @exp.work_type
                  }

  end


  def update_exp

    @exp=Experience.find_by_id(params[:id])

    @exp.update(exp_params)

    redirect_to "/resume"

  end


  def create_avatar




    @user=User.find_by_id(current_user.id)

    User.establish_connection()

    @user.avatar = params[:file]


    @user.save


    redirect_to "/resume"


  end



  protected

  def base_info_params

  params.require(:base_info).permit(:name,:age,:sex,:is_married,:weight,:c_number)

  end

  def contact_params

    params.require(:contact).permit(:home,:phone,:qq,:email,:postalcode)
  end


  def edu_params

    params.require(:education).permit(:school,:level,:end_time,:begin_time,:profession)
  end


  def exp_params
    params.require(:experience).permit(:company,:work,:end_time,:begin_time,:work_type)
  end

end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/resume/show.erb
<div class="container">


  <div class="vacancy">

<div class="col-xs-12">

<div class="module">

    <div class="resume-panel ">
      <div class="panel-header clearfix">
        <h4>基本信息</h4>
        <% if company_signed_in?%>
            <% if @Interview[0].is_invited %>
                <a disabled> 已邀请面试</a>
             <%elsif @Interview[0].is_refused  %>

                <a disabled class="btn-default"> 已拒绝 </a>

                <% else%>
        <a href="/interview/invite/<%=@Interview[0].id %>" class="btn btn-primary">邀请面试</a>
        <a href="/interview/refuse/<%=@Interview[0].id%>" class="btn btn-default ">拒绝</a>

            <%end%>
        <%end%>

      </div>


      <ul class="info-list clearfix" >

            <li> <label>姓名：</label><span><%=@base_info.name %></span></li>
            <li class="clearfix"> <label>年龄：</label><span><%=@base_info.age %></span></li>
            <li> <label>性别：</label><span><%=@base_info.sex %></span></li>
            <li> <label>体重：</label><span><%=@base_info.weight%></span></li>
            <li> <label>户口所在地：</label><span><%=@base_info.location %></span></li>
            <li> <label>身份证号码：</label><span><%=@base_info.c_number %></span></li>
            <li> <label>婚姻状况:</label><span><%=@base_info.is_married %></span></li>

      </ul>




    </div>

    <div class="resume-panel grey-panel">

      <div class="panel-header clearfix">
        <h4>联系信息</h4>

      </div>




      <ul class="info-list clearfix" >

            <li> <label>手机：</label><span><%= @contact.phone %></span></li>
            <li> <label>QQ：</label><span><%= @contact.qq %></span></li>
            <li> <label>邮箱：</label><span><%= @contact.email %></span></li>
            <li> <label>通讯地址：</label><span><%= @contact.home %></span></li>
            <li> <label>邮政编码：</label><span><%= @contact.postalcode %></span></li>

      </ul>




    </div>
    <div class="resume-panel">

      <div class="panel-header clearfix">
        <h4>教育经历</h4>

      </div>


      <table class="table" >

            <thead><tr>
              <td>学校名称</td>
              <td>专业名称</td>
              <td>就读时间</td>
              <td>学位</td>

            </tr></thead>
            <tbody>
            <% @edu.each do |e|	  %>
                <tr>
                  <td><%=e.school %></td>
                  <td><%=e.profession %></td>
                  <td><%=e.begin_time %>-- <%=e.end_time %></td>
                  <td><%=e.level %></td>
                  <td> <button class="btn btn-xs btn-primary" onclick="edit_edu('<%=e.id %>')">编辑</button>
                  </td>
                </tr>

            <% end %>

            </tbody>



      </table>



    </div>

    <div class="resume-panel grey-panel">
      <div class="panel-header clearfix">
        <h4>
          实习经历
        </h4>

      </div>

      <table class="table" >

            <thead>
            <tr>
              <td>工作单位</td>
              <td>工作名称</td>
              <td>职位类型</td>
              <td>在职时间</td>

            </tr>
            </thead>
            <tbody>
            <%@exp.each do |e| %>
                <tr>
                  <td><%=e.company %></td>
                  <td><%=e.work %></td>

                  <td><%=e.work_type %></td>
                  <td><%=e.begin_time %>-<%=e.end_time%></td>


                </tr>
            <%end %>

            </tbody>

      </table>



    </div>

</div>


</div>

  </div>


</div>